
name: My Workflow

on: 
  push:
  pull_request:

jobs:

build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Job Script
        run: echo "ram and amar !"

  ram:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ram Job Script
        run: echo "Hello from Ram prasad!"

  amar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Amar Job Script
        run: echo "Hello from Amar!"

