
name: My Workflow

on: 
  push:       # Trigger
  pull_request:

jobs:
  build_ama:
    needs: build_ram  # Correct dependency
    runs-on: ubuntu-latest   # Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Prebuilt action

      - name: Run script
        run: echo "Hello GitHub Actions!"
  build_ram:
    runs-on: ubuntu-latest   # Runner

    steps:
      - name: Amar
        uses: actions/checkout@v3   # Prebuilt action

      - name: Run script
        run: echo "Hello GitHub Actions!"
  build_lakshmi:
    needs: build_ama   # Correct dependency
    runs-on: ubuntu-latest   # Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3   # Prebuilt action

      - name: Run script
        run: echo "Hello GitHub Actions!"